server:
  port: @server.port@
eureka:
  instance:
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: @defaultZone@
    registryFetchIntervalSeconds: 5         #eureka client刷新本地缓存时间
spring:
  application:
    name: gateway
  #DATABASE CONFIG
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: qdm169445471
    password: wangyidan1
    url: jdbc:mysql://qdm169445471.my3w.com:3306/qdm169445471_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      #ddl-auto: create #ddl-auto:设为create表示每次都重新建表
      ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
    show-sql: true
#  zipkin:
#      enabled: true
#  sleuth:
#    sampler:
#      percentage: 0.2
zuul:
  ignored-services: "*"
  sensitive-headers: x-user-id,x-access-client,x-case-ticket                  #忽略cookies 会话保持
  add-host-header: true               #后端重定向不改变host
#  prefix: /api #公共的前缀

#
##clientId和isJwt必填其一
#xcloud:
#  oauth2:
#  #配置下面两项即启用远程token验证 否则保持redis为同一集群
#    clientId: ${spring.application.name}
#    clientSecret: 123456
#  #配置此项启用jwtToken 不需要远程或redis读取验证token 为true时clientId配置无效
#    isJwt: false
#  basic:
#    enabled: true
#    path: /manage
#  user:
#    name: admin
#    password: admin
#  anno:
##    完全访问
#    permitAll:
#      - /**/error
#      - /sysLog**/**

#ribbon:
#  eager-load:
#    enabled: true
#    clients: xcloud-user
#  readTimeout: 5000
#  connectTimeout: 5000
#  httpclient.enabled: false
#  okhttp.enabled: true

