
spring:
  #DATABASE CONFIG
  application:
    name: springms-provider-user-mysql-jdbctemplate  #全部小写
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: qdm169445471
    password: wangyidan1
    url: jdbc:mysql://qdm169445471.my3w.com:3306/qdm169445471_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
  zipkin:
      enabled: true
  sleuth:
    sampler:
      percentage: 0.2

eureka:
  client:
    healthcheck:
      enabled: true
#
##clientId和isJwt必填其一
#xcloud:
#  oauth2:
#  #配置下面两项即启用远程token验证 否则保持redis为同一集群
#    clientId: ${spring.application.name}
#    clientSecret: 123456
#  #配置此项启用jwtToken 不需要远程或redis读取验证token 为true时clientId配置无效
#    isJwt: false
#  basic:
#    enabled: true
#    path: /manage
#  user:
#    name: admin
#    password: admin
#  anno:
##    完全访问
#    permitAll:
#      - /**/error
#      - /sysLog**/**

ribbon:
  eager-load:
    enabled: true
    clients: xcloud-user
  readTimeout: 5000
  connectTimeout: 5000
#  httpclient.enabled: false
#  okhttp.enabled: true

